"""List of IT job titles for filtering."""

IT_JOB_TITLES = [
    "Software Engineer",
    "Software Developer",
    "Application Developer",
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Application Developer",
    "Game Developer",
    "API Developer",
    "Embedded Systems Engineer",
    "Firmware Engineer",
    "DevOps Engineer",
    "Build Engineer",
    "Release Engineer",
    "IT Support Specialist",
    "Help Desk Technician",
    "Desktop Support Technician",
    "Technical Support Engineer",
    "IT Technician",
    "Field Service Technician",
    "System Administrator",
    "Linux Administrator",
    "Windows Administrator",
    "Network Administrator",
    "Network Engineer",
    "Infrastructure Technician",
    "Cybersecurity Analyst",
    "Information Security Analyst",
    "Security Engineer",
    "Security Architect",
    "Penetration Tester",
    "Ethical Hacker",
    "SOC Analyst",
    "Incident Responder",
    "Digital Forensics Analyst",
    "Threat Intelligence Analyst",
    "Vulnerability Analyst",
    "Chief Information Security Officer",
    "CISO",
    "Data Analyst",
    "Data Scientist",
    "Data Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Research Scientist",
    "Business Intelligence Analyst",
    "BI Analyst",
    "BI Developer",
    "Database Administrator",
    "DBA",
    "Database Developer",
    "Data Architect",
    "Cloud Engineer",
    "Cloud Developer",
    "Cloud Architect",
    "Solutions Architect",
    "Systems Engineer",
    "Site Reliability Engineer",
    "SRE",
    "Platform Engineer",
    "Infrastructure Engineer",
    "Virtualization Engineer",
    "IT Manager",
    "IT Director",
    "IT Project Manager",
    "Program Manager",
    "Product Manager",
    "Engineering Manager",
    "Scrum Master",
    "Agile Coach",
    "Chief Information Officer",
    "CIO",
    "Chief Technology Officer",
    "CTO",
    "QA Engineer",
    "Software Tester",
    "Automation Test Engineer",
    "Performance Engineer",
    "UX Designer",
    "UI Designer",
    "UX Researcher",
    "Technical Writer",
    "Systems Analyst",
    "Business Analyst",
    "ERP Consultant",
    "CRM Consultant",
    "IT Auditor",
    "Compliance Analyst",
    "Robotics Engineer",
    "Blockchain Developer",
    "AR/VR Developer",
    "Junior Software Developer",
    "Junior Data Analyst",
    "IT Intern",
    "Help Desk Analyst",
    "Support Technician",
    "Junior QA Tester"
]

def is_it_job(title: str) -> bool:
    """Check if a job title matches any of the IT job titles (case-insensitive)."""
    title_lower = title.lower()
    for it_title in IT_JOB_TITLES:
        if it_title.lower() in title_lower:
            return True
    return False
