name: Run Scraper

on:
  schedule:
    # Har 6 ghante chalega
    - cron: '0 */6 * * *'

  # Manually bhi run kar sakte ho
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Call Scraper API
        run: |
          curl -X GET https://job-scraper-dc89.onrender.com/scrape
